firstwebsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/urls.py
from django.conf.urls import url
from . import views
app_name = 'music'

urlpatterns = [

    # /music/
    url(r'^$', views.index, name='index'),

    # /music/album.id/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),

    # /music/album.id/favorite/
    url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
]

music/models.py
from django.db import models


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.artist


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=100)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import get_object_or_404
from django.shortcuts import render
from .models import Album, Song


def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})


def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album': album})


def favorite(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    try:
        selected_song = album.song_set.get(pk=request.POST['song'])
    except(KeyError, Song.DoesNotExist):
        return render(request, 'music/detail.html', {
            'album': album,
            'error_message': 'Select a valid song',
        })
    else:
        selected_song.is_favorite = True
        selected_song.save()
        return render(request, 'music/detail.html', {'album': album})

music/templates/music/detail.html
<img src = "{{ album.album_logo }}" height="100" width="100">

<h1>{{album.album_title}}</h1>
<h2>{{album.artist}}</h2>

{% if error_message %}
    <p><strong>{{ error_message }}</strong></p>
    {% endif %}

<form action="{% url 'music:favorite' album.id %}" method="post">
    {% csrf_token %}

    {% for song in album.song_set.all %}
    <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}">
    <label for="song{{ forloop.counter }}">
        {{ song.song_title }}
        {% if song.is_favorite %}
            <img src="https://cdn3.iconfinder.com/data/icons/flat-actions-icons-9/792/Star_Gold-512.png" height="16" width="16"/>
        {% endif %}
    </label><br>
    {% endfor %}
    <input type="submit" value="Favorite">
</form>

music/templates/music/index.html
<!-- load static path -->
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />

<nav class="navbar navbar-default">
    <div class="container-fluid">

        <!--logo-->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'music:index' %}">viberr</a>

        </div>

    </div>

</nav>


{% if all_albums %}
<ul>
    <h3>Your albums</h3>
    {% for album in all_albums %}
    <li><a href=" {% url 'music:detail' album.id %} "> {{ album.album_title }}</a></li>
    {% endfor %}
</ul>

{% else %}
    <h3> No albums to display :( </h3>
{% endif %}